<?php

namespace AppBundle\Repository;

/**
 * AppartenirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartenirRepository extends \Doctrine\ORM\EntityRepository
{
}
