<?php

namespace AppBundle\Repository;

/**
 * ContenirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenirRepository extends \Doctrine\ORM\EntityRepository
{
}
